numero_1 = input("Digite um número: ")
numero_2 = input("Digite outro número: ")
resultado = float(numero_1) + float(numero_2)
resultado2 = float(numero_1) - float(numero_2)
resultado3 = float(numero_1) * float(numero_2)
resultado4 = float(numero_1) / float(numero_2)

print()
print(resultado)
print(resultado2)
print(resultado3)
print(resultado4)